plugins {
    id "com.diffplug.spotless" version "8.1.0" apply false
    id "org.gradlex.extra-java-module-info" version "1.14.2" apply false
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'com.diffplug.spotless'
    apply plugin: 'org.gradlex.extra-java-module-info'

    repositories {
        mavenCentral()
    }

    extraJavaModuleInfo {
        failOnMissingModuleInfo = false
        skipLocalJars = true
        automaticModule('org.flywaydb:flyway-core', 'flyway.core')
    }

    spotless {
        java {
            removeUnusedImports()
            palantirJavaFormat()
        }
    }

    dependencies {
        testImplementation('junit:junit:4.13')
        testImplementation("org.assertj:assertj-core:3.27.6")
        testImplementation('org.mockito:mockito-core:5.21.0')

        api('org.slf4j:slf4j-api:2.0.17')
        implementation('ch.qos.logback:logback-classic:1.5.22')
        compileOnly('org.jspecify:jspecify:1.0.0')
        compileOnly('org.jetbrains:annotations:26.1.0')
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
            vendor = JvmVendorSpec.ADOPTIUM
        }
    }

    if (!System.getenv('CI')) {
        tasks.withType(JavaCompile).configureEach {
            dependsOn 'spotlessApply'
        }
    }
}
