plugins {
    id "com.diffplug.spotless" version "8.1.0" apply false
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'com.diffplug.spotless'

    repositories {
        mavenCentral()
    }

    spotless {
        java {
            removeUnusedImports()
            palantirJavaFormat()
        }
    }

    dependencies {
        testImplementation('junit:junit:4.13')
        testImplementation("org.assertj:assertj-core:3.27.6")
        testImplementation('org.mockito:mockito-core:5.21.0')

        api('org.slf4j:slf4j-api:2.0.17')
        implementation('ch.qos.logback:logback-classic:1.5.22')
        api('com.google.guava:guava:33.5.0-jre')
        compileOnly('org.jspecify:jspecify:1.0.0')
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
            vendor = JvmVendorSpec.ADOPTIUM
        }
    }

    if (!System.getenv('CI')) {
        tasks.withType(JavaCompile).configureEach {
            dependsOn 'spotlessApply'
        }
    }
}
