/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.selesse.steam.crossplatform.sync;

import com.selesse.steam.crossplatform.sync.config.GameLoader;
import com.selesse.steam.crossplatform.sync.config.SteamCrossplatformSync;
import com.selesse.steam.crossplatform.sync.config.SteamCrossplatformSyncConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.nio.file.Path;

public class App {
    private static final Logger LOGGER = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        SteamCrossplatformSyncConfig config = SteamCrossplatformSync.loadConfiguration();
        GameConfig gameList = new GameLoader().loadGames(config);
        gameList.getGames().forEach(game -> {
            Path localPath = game.getLocalPath();
            Path cloudSyncPath = game.getLocalCloudSyncPath(config);

            LOGGER.info("Checking {}", game.getName());
            GameSyncer.sync(localPath, cloudSyncPath);
        });
    }
}
