plugins {
    id "de.undercouch.download" version "4.1.1"
    id 'java-library'
}

dependencies {
    implementation(project(':common'))
    implementation("tools.jackson.core:jackson-core:3.0.3")
    implementation("tools.jackson.core:jackson-databind:3.0.3")

    testImplementation("tools.jackson.dataformat:jackson-dataformat-yaml:3.0.3")
}

task downloadSteamCmd(type: Download) {
    src(['https://steamcdn-a.akamaihd.net/client/installer/steamcmd_osx.tar.gz',
            'https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip'])
    dest buildDir
    onlyIfModified true
}
